<?php

namespace AppBundle\Repository;

/**
 * ChangePasswordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangePasswordRepository extends \Doctrine\ORM\EntityRepository
{
}
