<?php

namespace AppBundle\Repository;

/**
 * ChangeAvatarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeAvatarRepository extends \Doctrine\ORM\EntityRepository
{
}
