<?php

namespace AppBundle\Repository;

/**
 * TransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActiveBy($userId)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT t FROM AppBundle:Transport t WHERE t.userId = :userId AND t.active = 1 ORDER BY t.id DESC')
            ->setParameter('userId', $userId)
            ->getResult();
    }

    public function findAllNotActive()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT u.avatar, u.username, u.roles, t.cargo, t.score, t.screenshot, t.startCity, t.endCity, t.endDate, t.id FROM AppBundle:Transport t, AppBundle:User u WHERE t.userId = u.id AND t.active = 0 ORDER BY u.roles ASC, t.id DESC')
            ->getResult();
    }

    public function findFiveActiveBy($userId)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT t FROM AppBundle:Transport t WHERE t.userId = :userId AND t.active = 1 ORDER BY t.id DESC')
            ->setParameter('userId', $userId)
            ->getResult();
    }
}
