<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDrivers()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT u.id, u.username, u.avatar, u.roles, SUM(t.burnedFuel) AS burnedFuel, SUM(t.distance) AS travelledDistance, COUNT(t) AS madedTransports, SUM(t.score) AS earnedMoney FROM AppBundle:Transport t, AppBundle:User u WHERE t.userId = u.id GROUP BY u.username ORDER BY u.roles ASC')
            ->getResult();
    }

    public function getMoney($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT SUM(t.score) FROM AppBundle:Transport t WHERE t.userId = :id AND t.active = 1')
            ->setParameter('id', $id)
            ->getSingleScalarResult();
    }

    public function getTransportsQuantity($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(t) FROM AppBundle:Transport t WHERE t.userId = :id AND t.active = 1')
            ->setParameter('id', $id)
            ->getSingleScalarResult();
    }

    public function getDistance($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT SUM(t.distance) FROM AppBundle:Transport t WHERE t.userId = :id AND t.active = 1')
            ->setParameter('id', $id)
            ->getSingleScalarResult();
    }

    public function getFuel($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT SUM(t.burnedFuel) FROM AppBundle:Transport t WHERE t.userId = :id AND t.active = 1')
            ->setParameter('id', $id)
            ->getSingleScalarResult();
    }
}
